import pandas as pd
#STRUCTURED DATA
data = {"NAME":['LOHIT_SHAN','LOKESH_SINGH','LOKESHWAR_PRASAD','LINGESHWARAN'],"AGE":[18,20,19,22],"ROLE":["CYBER-SECURITY_ANALYST","SOFTWARE_ENGINEER","UI/UX_DESIGNER","DATA_ANALYST"]}
df = pd.DataFrame(data)
print(df)

#UNSTRUCTURED DATA
info = {"LOHIT_SHAN 18 CYBER-SECURITY_ANALYST ","LOKESH_SINGH 20 SOFTWARE_ENGINEER","LOKESHWAR_PRASAD 19 UI/UX_DESIGNER","LINGESHWARAN 22 DATA_ANALYST"}
fd = pd.DataFrame(info)
print(fd)

#SEMI-STRUCTURED DATA
coll = {"EMPLOYEE" : [
    {"NAME":"LOHIT_SHAN","AGE":18,"ROLE":"CYBER-SECURITY_ANALYST"},
    {"NAME":"LOKESH_SINGH","AGE":20,"ROLE":"SOFTWARE_ENGINEER"},
    {"NAME":"LOKESHWAR_PRASAD","AGE":19,"ROLE":"UI/UX_DESIGNER"},
    {"NAME":"LINGESHWARAN","AGE":22,"ROLE":"DATA_ANALYST"},]}
ff = pd.DataFrame(coll)
print(ff)
